### ISSUE TITLE
Opera extension is gone

### ISSUE THREAD

**Issue by szabota** [PyvesB/NightVideoTuner#2]
Your extension has disappeared from the Opera Add-Ons Store. There is only a 404 error by this link: [https://addons.opera.com/extensions/details/night-video-tuner](https://addons.opera.com/extensions/details/night-video-tuner)
And also a search for the keywords "Night Video Tuner" does not give the desired result in there.
![404](https://user-images.githubusercontent.com/44994472/95588921-b1b2a800-0a4c-11eb-9655-c96b4720bf98.png)

**Comment by PyvesB** [comment]
Hello @szabota! 👋🏻 

Thanks for pointing this out.

Unfortunately, Opera deleted my account and extensions, apparently due to me not logging in for a while. To be fair, looking back at my inbox, they did warn about this, but it was a single mail, sent in the middle of August, with only a couple of weeks notice. There was no indication that this was going to affect extensions, Firefox and Chrome keep the dev and user account parts separate. There was no other form of communication nor confirmation.

This doesn't feel right. I've wrote something up for Opera support using [this form](https://www.opera.com/fr/contact/support-form), but after filling in all the  fields and the captcha, and pressing confirm, nothing happens. The browser console indicates a 403 error response code from the Opera servers. The contact form is broken. 😕

**Comment by PyvesB** [comment]
I tried contacting them via their official Twitter account instead. Let's see what comes out of that.

**Comment by PyvesB** [comment]
No response from Opera on Twitter, it's been a week now. The contact link is still broken as well. Unfortunately, I'll have to drop Opera support.

On the bright side, you can install Chrome extensions on Opera, simply check this page out: https://addons.opera.com/fr/extensions/details/install-chrome-extensions/ :wink:
